import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Sans_JP } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import { Toaster } from "@/components/ui/sonner";

const myFont = localFont({
  src: [
    {
      path: "../public/fonts/gotham-bold.woff2",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-gotham",
});

export const jpFont = Noto_Sans_JP({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-jp',
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// const poppins = Poppins({
//   subsets: ["latin"],
//   weight: ["300", "400", "500", "600", "700"],
//   variable: "--font-poppins",
//   display: "swap",
// });

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`dark`}>
      <body
        className={`${geistSans.variable} ${jpFont.variable} ${geistMono.variable} ${myFont.variable} antialiased`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
